main: com.zyxkon.judgmentday.Main
name: JudgmentDay
version: 1.0
description: A zombie apocalypse plugin.
author: Zyxkon
softdepend: [WorldGuard, CrackShot, WorldEdit]
commands:
  zyxkon:
    usage: /zyxkon
    description: This command was implemented for testing purpose.