main: com.zyxkon.judgmentday.Main
name: JudgmentDay
version: 2.0
description: A zombie apocalypse plugin.
author: Zyxkon
softdepend: [WorldGuard, CrackShot, WorldEdit]
commands:
  zyxkon:
    usage: /zyxkon
    description: This command was implemented for testing purpose.
  JudgmentDay:
    aliases: [jd, judgmentday]
    usage: /judgmentday
    description: Command for the JudgmentDay plugin.