main: zyxkon.judgmentday.Main
name: JudgmentDay
version: 1.0
description: A zombie apocalypse plugin.
author: Zyxkon
commands:
  zyxkon:
    usage: /zyxkon
    description: This command was implemented for testing purpose.